name: Monthly Data Updater

on:
  schedule:
    - cron: '0 6 1 * *'  # Runs at midnight central time first of each month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install pandas openpyxl

      - name: Run cleaning script on Excel data
        run: |
          python datacleaning.py data/Support_Application_data.xlsx

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*  # Ensure all files in the data folder are tracked
          git commit -m "Monthly data update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
