name: Auto Clean Uploaded Data

on:
  push:
    branches:
      - main
    paths:
      - '**/*.csv'
      - '**/*.xlsx'
      - '!data/uszips.csv'  # Exclude this file

permissions:
  contents: write

jobs:
  clean-up-job:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository files
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install pandas numpy openpyxl

      - name: Identify changed data files
        id: find_files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.csv$|\.xlsx$' || true)
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Print Files Being Processed
        run: |
          echo "Files being processed: $FILES"

      - name: Run data cleaning script for each file
        if: env.FILES != ''
        run: |
          for FILE in $FILES; do
            echo "Running cleaner on: $FILE"
            python datacleaning.py "$FILE"
          done

      - name: Save cleaned output
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *_CLEANED.csv
          git commit -m "Cleaned files update"
          git push
        continue-on-error: true
